version: '3.3' # Change this if needed

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban

volumes:
  postgres_data: {}